name: firmware
on:
  schedule:
    # 01:15 PST / Nightly
    - cron:  '15 8 * * *'
  workflow_dispatch:
    inputs:
      tg_disabled:
        type: boolean
        description: 'Disable Telegram notifications'
        required: false
        default: false
      tg_scratch:
        type: boolean
        description: 'Use TG scratch channel'
        required: false
        default: false
      graph_enabled:
        type: boolean
        description: 'Enable build time graph'
        required: false
        default: false
      teacup_only:
        type: boolean
        description: 'Only build Tea Cup profile'
        required: false
        default: false
      debug_only:
        type: boolean
        description: 'Debug: Generate dummy image files'
        required: false
        default: false

env:
  TAG_NAME: firmware
  TERM: linux
  BR2_DL_DIR: ~/dl
  FORCE_UNSAFE_CONFIGURE: 1

jobs:
  buildroot:
    name: ahc-3301y-ht1
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    container:
      image: debian:bookworm
    steps:
      - name: Update APT sources
        run: |
          apt-get update

      - name: Install build dependencies
        run: |
          apt-get install -y --no-install-recommends --no-install-suggests build-essential bc cmake cpio curl ca-certificates file git make gawk procps rsync u-boot-tools unzip wget

      - name: Setup gh workspace in container
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Checkout source
        uses: actions/checkout@v4
        with:
          submodules: 'true'
          ref: "master"
          fetch-depth: "1"

      - name: Setup Environment
        id: date
        run: |
          echo "WEEK_NUMBER=$(date +%U)" >> $GITHUB_ENV
          echo "CURRENT_YEAR=$(date +%Y)" >> $GITHUB_ENV
          export GIT_HASH=$(git rev-parse --short ${GITHUB_SHA})
          export GIT_BRANCH=${GITHUB_REF_NAME}
          echo "GIT_HASH=${GIT_HASH}" >> ${GITHUB_ENV}
          echo "GIT_BRANCH=${GIT_BRANCH}" >> ${GITHUB_ENV}
          echo "TAG_NAME=$TAG_NAME-$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Setup cache directories
        run: |
          mkdir -p ~/.ccache
          mkdir -p ~/dl

      - name: Restore build cache
        uses: actions/cache@v4
        if: always()
        with:
          path: ~/.ccache
          key: ${{ runner.os }}-ccache-ahc-3301y-ht1-${{ env.CURRENT_YEAR }}-week-${{ env.WEEK_NUMBER }}-${{ github.run_id }}
          restore-keys: |
            ${{ runner.os }}-ccache-ahc-3301y-ht1-${{ env.CURRENT_YEAR }}-week-${{ env.WEEK_NUMBER }}
            ${{ runner.os }}-ccache-ahc-3301y-ht1-${{ env.CURRENT_YEAR }}-week-
            ${{ runner.os }}-ccache-ahc-3301y-ht1-
            ${{ runner.os }}-ccache-
            ${{ runner.os }}-ccache-shared-v1-${{ env.CURRENT_YEAR }}-week-${{ env.WEEK_NUMBER }}

      - name: Restore Buildroot DL cache
        uses: actions/cache/restore@v4
        if: always()
        with:
          path: ~/dl
          key: ${{ runner.os }}-dl-shared-v1-${{ env.CURRENT_YEAR }}-week-${{ env.WEEK_NUMBER }}

      - name: Build firmware
        run: |
          BOARD=ahc-3301y-ht1 make fast
          TIME=$(date -d @${SECONDS} +%M:%S)
          echo "TIME=${TIME}" >> ${GITHUB_ENV}

      - name: Upload update firmware artifact
        uses: actions/upload-artifact@v4
        with:
          name: thingino-ahc-3301y-ht1
          path: ~/output/ahc-3301y-ht1/images/
